In [3]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2
import datetime

In [4]:
#define index of labels?

## Load the training data into feature matrix, class labels, and event ids:

In [5]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'D:\\Jupyter Notebook\Machine Learning\project1\data\\train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [6]:
y.shape,tX.shape,ids.shape

((250000,), (250000, 30), (250000,))

In [7]:
tX[:,1]

array([ 51.655,  68.768, 162.172, ...,  60.526,  19.362,  72.756])

## Do your thing crazy machine learning thing here :) ...

In [8]:
#Compute Transverse Mass 
def transverse_mass(a_t,a_phi,b_t,b_phi):
    
    
    mass = np.sqrt((a_t+b_t)**2-(a_t*np.cos(a_phi)+b_t*np.cos(b_phi))**2-(a_t*np.sin(a_phi)+b_t*np.sin(b_phi))**2)
    
    
    return mass

In [29]:
#transverse_mass test
print(transverse_mass(tX[:,19],tX[:,20],tX[:,16],tX[:,18]))
print(tX[:,1])
print((transverse_mass(tX[:,19],tX[:,20],tX[:,16],tX[:,18])-tX[:,1]).mean())

[ 51.66192009  68.78329787 162.174512   ...  60.52079714  19.36191784
  72.75137486]
[ 51.655  68.768 162.172 ...  60.526  19.362  72.756]
nan


C:\DEVELOPMENT\anconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


In [10]:
#Compute Invariant mass
def invariant_mass(a_t,a_eta,a_phi,b_t,b_eta,b_phi):
    a_z = a_t*np.sinh(a_eta)
    b_z = b_t*np.sinh(b_eta)
    
    a_xyz = np.sqrt(a_t**2+(a_z)**2)
    b_xyz = np.sqrt(b_t**2+(b_z)**2)
    ab_x = a_t*np.cos(a_phi)+b_t*np.cos(b_phi)
    ab_y =a_t*np.sin(a_phi)+b_t*np.sin(b_phi)
    ab_z =a_z+b_z
    
    
    mass = np.sqrt((a_xyz+b_xyz)**2-(ab_x)**2-(ab_y)**2-(ab_z)**2)
    
    return mass

In [27]:
#invariant mass test
print(invariant_mass(tX[:,13],tX[:,14],tX[:,15],tX[:,16],tX[:,17],tX[:,18]))
print(tX[:,2])
print((invariant_mass(tX[:,13],tX[:,14],tX[:,15],tX[:,16],tX[:,17],tX[:,18])-tX[:,2]).mean())

[ 97.80554839 103.22216251 125.92230193 ...  75.82162756  68.79599297
  70.82931157]
[ 97.827 103.235 125.953 ...  75.839  68.812  70.831]
-0.01725799703735722


In [12]:
#Compute Modulus of vecotr sum
def modulus_vector(a_t,a_phi,b_t,b_phi,c_met,c_phi):
    
    x = a_t*np.cos(a_phi)+b_t*np.cos(b_phi)+c_met*np.cos(c_phi)
    y = a_t*np.sin(a_phi)+b_t*np.sin(b_phi)+c_met*np.sin(c_phi)
    
    
    p_t = np.sqrt(x**2+y**2)
    
    modulus = p_t*1.0
    return modulus
    

In [13]:
#modulus of the vector sum test
print(modulus_vector(tX[:,13],tX[:,15],tX[:,16],tX[:,18],tX[:,19],tX[:,20]))
print(tX[:,3])

[27.94739991 48.12297042 35.62593902 ... 39.78224526 13.5098374
  7.47152233]
[27.98  48.146 35.635 ... 39.757 13.504  7.479]


In [21]:
#Compute Pseudorapidity Separation
def pseudorapidity_separation(jet_num,leading_eta,subleading_eta):
    
    
    N = len(leading_eta)
    sep = np.zeros(N)
    for t in range(N):
        if(jet_num[t]<=1):
            sep[t] = -999
        else:
            sep[t] = np.abs(leading_eta[t] - subleading_eta[t])
    return sep

In [28]:
#P Separation Test
print(pseudorapidity_separation(tX[:,22],tX[:,24],tX[:,27]))
print(tX[:,4])
print((pseudorapidity_separation(tX[:,22],tX[:,24],tX[:,27])-tX[:,4]).mean())

[ 9.10e-01 -9.99e+02 -9.99e+02 ... -9.99e+02 -9.99e+02 -9.99e+02]
[ 9.10e-01 -9.99e+02 -9.99e+02 ... -9.99e+02 -9.99e+02 -9.99e+02]
3.0000000000019655e-07


### Sometests

In [ ]:
#How to derive feature: DER_mass_transverse_met_lep from other features
#

### Data Cleaning

array([[ 138.47 ,   51.655,   97.827, ...,    1.24 ,   -2.475,  113.497],
       [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       ...,
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
       [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
       [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]])

In [18]:
from stochastic_gradient_descent import *

# Define the parameters of the algorithm.
max_iters = 300
gamma = 1e-7
batch_size = 100

# Initialization
w_initial = np.zeros(30)

# Start SGD.
start_time = datetime.datetime.now()
sgd_losses, sgd_ws = stochastic_gradient_descent(
    y, tX, w_initial, batch_size, max_iters, gamma)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("SGD: execution time={t:.3f} seconds".format(t=exection_time))

SGD(0/299): loss=0.44621888821528416
SGD(1/299): loss=0.43783224666640025
SGD(2/299): loss=0.43708833178048295
SGD(3/299): loss=0.4360985526326618
SGD(4/299): loss=0.435738410700349
SGD(5/299): loss=0.43708527307325534
SGD(6/299): loss=0.4353847931871214
SGD(7/299): loss=0.4347990636696359
SGD(8/299): loss=0.4344113955200877
SGD(9/299): loss=0.43329535901501054
SGD(10/299): loss=0.43387755449547905
SGD(11/299): loss=0.4356372099609092
SGD(12/299): loss=0.4317364524955887
SGD(13/299): loss=0.4336737680583843
SGD(14/299): loss=0.43021140466328617
SGD(15/299): loss=0.4301531725329095
SGD(16/299): loss=0.4315067867751375
SGD(17/299): loss=0.4303715027365334
SGD(18/299): loss=0.4287066330906592
SGD(19/299): loss=0.428401620093317
SGD(20/299): loss=0.43032374547737773
SGD(21/299): loss=0.429453811023959
SGD(22/299): loss=0.42823430438253995
SGD(23/299): loss=0.4281198262742519
SGD(24/299): loss=0.42867962580858476
SGD(25/299): loss=0.42694994727834584
SGD(26/299): loss=0.4271211390104495
SGD

SGD(217/299): loss=0.42533752080866283
SGD(218/299): loss=0.4170397297314473
SGD(219/299): loss=0.41453656225551877
SGD(220/299): loss=0.4135158660007663
SGD(221/299): loss=0.41133916007055554
SGD(222/299): loss=0.4109925970214171
SGD(223/299): loss=0.41148019662322277
SGD(224/299): loss=0.41129581023906353
SGD(225/299): loss=0.4114942564654783
SGD(226/299): loss=0.4119920920419788
SGD(227/299): loss=0.4106285980524343
SGD(228/299): loss=0.41194354956836304
SGD(229/299): loss=0.41053162167351603
SGD(230/299): loss=0.41152179117251786
SGD(231/299): loss=0.41159968808083397
SGD(232/299): loss=0.4111419078782423
SGD(233/299): loss=0.4118036082437149
SGD(234/299): loss=0.4124045708325791
SGD(235/299): loss=0.4109886184174132
SGD(236/299): loss=0.41116069293196633
SGD(237/299): loss=0.4104425117780421
SGD(238/299): loss=0.41018485663708854
SGD(239/299): loss=0.4100682349692056
SGD(240/299): loss=0.4105936086021653
SGD(241/299): loss=0.4109621611355064
SGD(242/299): loss=0.41262880607035607


In [12]:
from gradient_descent import *
from plots import gradient_descent_visualization

# Define the parameters of the algorithm.
max_iters = 1000
gamma = 1e-7

# Initialization
w_initial = np.random.uniform(size=30)

# Start gradient descent.
start_time = datetime.datetime.now()
gradient_losses, gradient_ws = gradient_descent(y, tX, w_initial, max_iters, gamma)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("Gradient Descent: execution time={t:.3f} seconds".format(t=exection_time))
    
    
    

Gradient Descent(0/999): loss=4026597.208806231
Gradient Descent(1/999): loss=858320.896280879
Gradient Descent(2/999): loss=278103.8668724276
Gradient Descent(3/999): loss=168869.76711567058
Gradient Descent(4/999): loss=145445.58778938354
Gradient Descent(5/999): loss=137750.43407121304
Gradient Descent(6/999): loss=133029.59443376292
Gradient Descent(7/999): loss=128958.17531372968
Gradient Descent(8/999): loss=125109.04764643247
Gradient Descent(9/999): loss=121400.56154920557
Gradient Descent(10/999): loss=117814.1184050088
Gradient Descent(11/999): loss=114342.77422178564
Gradient Descent(12/999): loss=110981.87652578918
Gradient Descent(13/999): loss=107727.34960038488
Gradient Descent(14/999): loss=104575.37214741267
Gradient Descent(15/999): loss=101522.30912237997
Gradient Descent(16/999): loss=98564.69058087931
Gradient Descent(17/999): loss=95699.19977692603
Gradient Descent(18/999): loss=92922.66358064636
Gradient Descent(19/999): loss=90232.04389708361
Gradient Descent(20

Gradient Descent(166/999): loss=3199.789962852331
Gradient Descent(167/999): loss=3160.30463392951
Gradient Descent(168/999): loss=3121.7766361895406
Gradient Descent(169/999): loss=3084.178997862635
Gradient Descent(170/999): loss=3047.485534289902
Gradient Descent(171/999): loss=3011.6708246813027
Gradient Descent(172/999): loss=2976.7101895649803
Gradient Descent(173/999): loss=2942.5796689072804
Gradient Descent(174/999): loss=2909.2560008833525
Gradient Descent(175/999): loss=2876.716601278893
Gradient Descent(176/999): loss=2844.939543504118
Gradient Descent(177/999): loss=2813.9035392016626
Gradient Descent(178/999): loss=2783.5879194306276
Gradient Descent(179/999): loss=2753.972616409573
Gradient Descent(180/999): loss=2725.0381458017
Gradient Descent(181/999): loss=2696.765589526051
Gradient Descent(182/999): loss=2669.1365790790023
Gradient Descent(183/999): loss=2642.133279350772
Gradient Descent(184/999): loss=2615.7383729221897
Gradient Descent(185/999): loss=2589.9350448

Gradient Descent(329/999): loss=1240.5381878165947
Gradient Descent(330/999): loss=1236.8252023995492
Gradient Descent(331/999): loss=1233.1372582591455
Gradient Descent(332/999): loss=1229.4740420056237
Gradient Descent(333/999): loss=1225.8352470986201
Gradient Descent(334/999): loss=1222.2205736619003
Gradient Descent(335/999): loss=1218.629728303379
Gradient Descent(336/999): loss=1215.0624239402675
Gradient Descent(337/999): loss=1211.5183796292017
Gradient Descent(338/999): loss=1207.9973204012035
Gradient Descent(339/999): loss=1204.4989771013445
Gradient Descent(340/999): loss=1201.0230862329645
Gradient Descent(341/999): loss=1197.569389806323
Gradient Descent(342/999): loss=1194.137635191548
Gradient Descent(343/999): loss=1190.7275749757634
Gradient Descent(344/999): loss=1187.3389668242733
Gradient Descent(345/999): loss=1183.9715733456812
Gradient Descent(346/999): loss=1180.625161960837
Gradient Descent(347/999): loss=1177.2995047754982
Gradient Descent(348/999): loss=117

Gradient Descent(492/999): loss=845.376731629218
Gradient Descent(493/999): loss=843.8267317263084
Gradient Descent(494/999): loss=842.284129207034
Gradient Descent(495/999): loss=840.7488839461016
Gradient Descent(496/999): loss=839.2209560762632
Gradient Descent(497/999): loss=837.7003059856122
Gradient Descent(498/999): loss=836.1868943149315
Gradient Descent(499/999): loss=834.6806819550955
Gradient Descent(500/999): loss=833.1816300445174
Gradient Descent(501/999): loss=831.689699966648
Gradient Descent(502/999): loss=830.2048533475196
Gradient Descent(503/999): loss=828.7270520533367
Gradient Descent(504/999): loss=827.2562581881105
Gradient Descent(505/999): loss=825.7924340913378
Gradient Descent(506/999): loss=824.3355423357228
Gradient Descent(507/999): loss=822.8855457249356
Gradient Descent(508/999): loss=821.4424072914196
Gradient Descent(509/999): loss=820.0060902942286
Gradient Descent(510/999): loss=818.5765582169096
Gradient Descent(511/999): loss=817.1537747654186
Gra

Gradient Descent(657/999): loss=666.14322725397
Gradient Descent(658/999): loss=665.4094375643184
Gradient Descent(659/999): loss=664.6787612782615
Gradient Descent(660/999): loss=663.9511823628033
Gradient Descent(661/999): loss=663.2266848690901
Gradient Descent(662/999): loss=662.5052529319576
Gradient Descent(663/999): loss=661.7868707694801
Gradient Descent(664/999): loss=661.0715226825251
Gradient Descent(665/999): loss=660.3591930543073
Gradient Descent(666/999): loss=659.6498663499475
Gradient Descent(667/999): loss=658.943527116033
Gradient Descent(668/999): loss=658.2401599801823
Gradient Descent(669/999): loss=657.5397496506089
Gradient Descent(670/999): loss=656.8422809156923
Gradient Descent(671/999): loss=656.1477386435467
Gradient Descent(672/999): loss=655.4561077815966
Gradient Descent(673/999): loss=654.7673733561519
Gradient Descent(674/999): loss=654.081520471987
Gradient Descent(675/999): loss=653.3985343119218
Gradient Descent(676/999): loss=652.7184001364041
Grad

Gradient Descent(822/999): loss=577.536042862627
Gradient Descent(823/999): loss=577.1495703536242
Gradient Descent(824/999): loss=576.7644360866425
Gradient Descent(825/999): loss=576.3806333047858
Gradient Descent(826/999): loss=575.9981552863745
Gradient Descent(827/999): loss=575.6169953447612
Gradient Descent(828/999): loss=575.237146828148
Gradient Descent(829/999): loss=574.8586031194021
Gradient Descent(830/999): loss=574.4813576358792
Gradient Descent(831/999): loss=574.1054038292388
Gradient Descent(832/999): loss=573.7307351852664
Gradient Descent(833/999): loss=573.3573452236965
Gradient Descent(834/999): loss=572.9852274980328
Gradient Descent(835/999): loss=572.6143755953734
Gradient Descent(836/999): loss=572.2447831362349
Gradient Descent(837/999): loss=571.8764437743769
Gradient Descent(838/999): loss=571.5093511966296
Gradient Descent(839/999): loss=571.1434991227196
Gradient Descent(840/999): loss=570.7788813050994
Gradient Descent(841/999): loss=570.4154915287745
Gr

Gradient Descent(988/999): loss=527.5654315280249
Gradient Descent(989/999): loss=527.3301539883747
Gradient Descent(990/999): loss=527.0954625578752
Gradient Descent(991/999): loss=526.8613543948605
Gradient Descent(992/999): loss=526.6278266724269
Gradient Descent(993/999): loss=526.3948765783555
Gradient Descent(994/999): loss=526.1625013150358
Gradient Descent(995/999): loss=525.9306980993891
Gradient Descent(996/999): loss=525.6994641627928
Gradient Descent(997/999): loss=525.4687967510051
Gradient Descent(998/999): loss=525.2386931240895
Gradient Descent(999/999): loss=525.0091505563403
Gradient Descent: execution time=198.645 seconds


In [23]:
len(sgd_ws)

301

In [24]:
weights=sgd_ws[300]

## Generate predictions and save ouput in csv format for submission:

In [19]:
DATA_TEST_PATH = 'D:\\Jupyter Notebook\Machine Learning\project1\data\\test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [25]:
OUTPUT_PATH = 'D:\\Jupyter Notebook\Machine Learning\project1\data\\submission_test1.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

array([[ 138.47 ,   51.655,   97.827, ...,    1.24 ,   -2.475,  113.497],
       [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       ...,
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
       [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
       [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]])